name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1

      - name: Build
        env:
          GO111MODULE: on  # Força o uso de módulos Go
        run: go build -o githp ./cmd/main.go

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO111MODULE: on
          GOARCH: arm64
          GOOS: linux
        with:
          args: |
            --tag v${{ github.run_number }}  # Define a tag
            --release-name "Release v${{ github.run_number }}"  # Nome da release
            --draft false
            --prerelease false

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload the Go binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./githp
          file_glob: false
